Ignore missing folder rather than fail.
net.twisterrob.inventory.android.data.svg.DumpImages > test[test(AVD) - 5.0.2] FAILED
        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.mkdirs()' on a null object reference