Fix category help not rendering on Pixel 7 Pro + fix crash on saving instance state:
(tws.CategoryHelpFragment)6dc62bd: 9020c05d-1e2c-4361-bdb8-6185d3085260.onSaveInstanceState2(Bundle of 2:
	BaseFragment.viewTag -> Intent of 10:
		cmp -> (ComponentName)ComponentInfo{net.twisterrob.inventory.debug/net.twisterrob.inventory.android.activity.MainActivity}
		xtra -> Bundle of 1: page -> "category-help"
	WEBVIEW_CHROMIUM_STATE -> (byte[976688])[44, -25, 14, 0, -92, 123, 51, 1, 2, 0, 0, 0, 1, 0, 0, 0, 25, 0, 0, 0, 100, 97, 116, 97, 58, 116, 101, 120, 116, 47, 104, 116, 109, 108, 44, 76, 111, 97, 100, 105, 110, 103, 46, 46, 46, 0, 0, 0, 25, 0, 0, 0, 100, 97, 116, 97, 58, 116, 101, 120, 116, 47, 104, 116, 109, 108, 44, 76, 111, 97, 100, 105, 110, 103, 46, 46, 46, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, -108, 2, 0, 0, -112, 2, 0, 0] and 976588 omitted)
BpBinder          W  Large outgoing transaction of 985092 bytes, interface descriptor <uncached descriptor>, code 5
JavaBinder        E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 985092)
ActivityStopInfo  W  Bundle stats:
ActivityStopInfo  W    android:viewHierarchyState [size=3300]
ActivityStopInfo  W      android:views [size=3252]
ActivityStopInfo  W        0x7f0900c7 [size=2112]
ActivityStopInfo  W    android:support:fragments [size=980976]
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 985092 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:89)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 985092 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1286)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)